name: Deploy to server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Add local env for build
        run: echo "NEXT_PUBLIC_VOL_SURFACE_API=${{ vars.BACKEND_DOMAIN_NAME }}" > .env.local

      - name: Install dependencies
        run: npm i

      - name: Build static site
        run: npm run build

      - name: Deploy to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/*"
          target: "/var/www/eashiryaev/"
          strip_components: 1
          rm: true